"use client";

import { useEffect, useRef, useState } from "react";
import toast from "react-hot-toast";
import html2canvas from "html2canvas";
import { QrCode, Download, ExternalLink, Printer } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useRestaurant } from "@/hooks/useRestaurant";
import { generateQRDataUrl, downloadPNG, getMenuUrl } from "@/lib/qrcode";
import { PageLoader } from "@/components/ui/Spinner";
import Image from "next/image";

export default function QRPage() {
  const { user } = useAuth();
  const { restaurant, loading } = useRestaurant(user?.uid ?? null);
  const [qrDataUrl, setQrDataUrl] = useState<string>("");
  const printCardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (restaurant?.slug) {
      const url = getMenuUrl(restaurant.slug);
      generateQRDataUrl(url).then(setQrDataUrl).catch(() => toast.error("Failed to generate QR code"));
    }
  }, [restaurant?.slug]);

  const handleDownload = () => {
    if (!qrDataUrl) return;
    downloadPNG(qrDataUrl, `${restaurant?.slug || "nemu"}-qr.png`);
    toast.success("QR code downloaded!");
  };

  const handlePrintCard = async () => {
    if (!printCardRef.current) return;
    try {
      const canvas = await html2canvas(printCardRef.current, { backgroundColor: "#ffffff", scale: 2, useCORS: true });
      downloadPNG(canvas.toDataURL("image/png"), `${restaurant?.slug || "nemu"}-menu-card.png`);
      toast.success("Menu card downloaded!");
    } catch {
      toast.error("Failed to generate print card");
    }
  };

  if (loading) return <PageLoader />;

  const menuUrl = restaurant?.slug ? getMenuUrl(restaurant.slug) : "";

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-black text-white font-display">QR Code</h1>
        <p className="text-slate-400 mt-1">Download and share your restaurant's QR code</p>
      </div>

      {!restaurant?.slug ? (
        <div className="glass-card p-8 rounded-2xl text-center" style={{ border: "1px solid rgba(255,255,255,0.06)" }}>
          <QrCode size={48} className="text-slate-500 mx-auto mb-4" />
          <h3 className="text-white font-bold text-lg mb-2">QR Code Not Ready</h3>
          <p className="text-slate-400 text-sm">Your QR code will be generated by the administrator after your account setup is complete.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* QR Preview */}
          <div className="glass-card p-6 rounded-2xl text-center space-y-4" style={{ border: "1px solid rgba(255,255,255,0.06)" }}>
            <h2 className="text-lg font-bold text-white">QR Code</h2>
            {qrDataUrl ? (
              <div className="bg-white p-4 rounded-2xl mx-auto w-fit shadow-xl shadow-indigo-500/10">
                <img src={qrDataUrl} alt="QR Code" className="w-48 h-48" />
              </div>
            ) : (
              <div className="w-48 h-48 mx-auto bg-slate-800 rounded-2xl animate-pulse" />
            )}

            <div className="flex gap-3">
              <button onClick={handleDownload} disabled={!qrDataUrl} className="btn-primary flex-1 py-2.5 rounded-xl text-sm flex items-center justify-center gap-2 disabled:opacity-50">
                <Download size={15} /> Download PNG
              </button>
              <button onClick={handlePrintCard} disabled={!qrDataUrl} className="flex-1 py-2.5 rounded-xl text-sm flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-700 text-white transition-colors disabled:opacity-50">
                <Printer size={15} /> Print Card
              </button>
            </div>
          </div>

          {/* Print Card Preview */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white">Printable Menu Card</h2>
            <p className="text-slate-400 text-sm">Download a print-ready card to place on your tables.</p>
            <div className="bg-slate-900/30 rounded-2xl p-4 border border-white/5">
              {/* The actual printable card */}
              <div
                ref={printCardRef}
                className="bg-white rounded-2xl overflow-hidden mx-auto"
                style={{ width: 300, fontFamily: "sans-serif" }}
              >
                {/* Card header */}
                <div style={{ background: "linear-gradient(135deg,#4f46e5,#7c3aed)", padding: "24px 20px", textAlign: "center" }}>
                  {restaurant.logo ? (
                    <img crossOrigin="anonymous" src={restaurant.logo} alt="logo" style={{ width: 60, height: 60, borderRadius: 12, margin: "0 auto 12px", objectFit: "cover" }} />
                  ) : (
                    <div style={{ width: 60, height: 60, borderRadius: 12, background: "rgba(255,255,255,0.2)", margin: "0 auto 12px", display: "flex", alignItems: "center", justifyContent: "center" }}>
                      <span style={{ fontSize: 28 }}>🍽️</span>
                    </div>
                  )}
                  <p style={{ color: "#ffffff", fontWeight: 800, fontSize: 20, margin: 0 }}>{restaurant.restaurantName}</p>
                </div>
                {/* QR Code */}
                <div style={{ padding: "24px 20px", textAlign: "center", background: "#ffffff" }}>
                  {qrDataUrl && <img src={qrDataUrl} alt="QR" style={{ width: 180, height: 180, margin: "0 auto" }} />}
                  <p style={{ color: "#6366f1", fontWeight: 800, fontSize: 18, marginTop: 16, marginBottom: 8 }}>Scan to View Menu</p>
                </div>
                {/* Footer */}
                <div style={{ background: "#f8fafc", padding: "10px 20px", textAlign: "center", borderTop: "1px solid #e2e8f0" }}>
                  <p style={{ color: "#94a3b8", fontSize: 10, margin: 0 }}>Powered by Nemu Digital Menu</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
