"use client";

import { useEffect, useRef, useState } from "react";
import toast from "react-hot-toast";
import html2canvas from "html2canvas";
import { QrCode, Download, ExternalLink, Printer } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useRestaurant } from "@/hooks/useRestaurant";
import { generateQRDataUrl, downloadPNG, getMenuUrl } from "@/lib/qrcode";
import { PageLoader } from "@/components/ui/Spinner";
import Image from "next/image";

export default function QRPage() {
  const { user } = useAuth();
  const { restaurant, loading } = useRestaurant(user?.uid ?? null);
  const [qrDataUrl, setQrDataUrl] = useState<string>("");
  const printCardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (restaurant?.slug) {
      const url = getMenuUrl(restaurant.slug);
      generateQRDataUrl(url).then(setQrDataUrl).catch(() => toast.error("Failed to generate QR code"));
    }
  }, [restaurant?.slug]);

  const handleDownload = () => {
    if (!qrDataUrl) return;
    downloadPNG(qrDataUrl, `${restaurant?.slug || "nemu"}-qr.png`);
    toast.success("QR code downloaded!");
  };

  const handlePrintCard = async () => {
    if (!printCardRef.current) return;
    try {
      const canvas = await html2canvas(printCardRef.current, { backgroundColor: "#ffffff", scale: 2, useCORS: true });
      downloadPNG(canvas.toDataURL("image/png"), `${restaurant?.slug || "nemu"}-menu-card.png`);
      toast.success("Menu card downloaded!");
    } catch {
      toast.error("Failed to generate print card");
    }
  };

  if (loading) return <PageLoader />;

  const menuUrl = restaurant?.slug ? getMenuUrl(restaurant.slug) : "";

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-black text-white font-display">QR Code</h1>
        <p className="text-slate-400 mt-1">Download and share your restaurant's QR code</p>
      </div>

      {!restaurant?.slug ? (
        <div className="glass-card p-8 rounded-2xl text-center" style={{ border: "1px solid rgba(255,255,255,0.06)" }}>
          <QrCode size={48} className="text-slate-500 mx-auto mb-4" />
          <h3 className="text-white font-bold text-lg mb-2">QR Code Not Ready</h3>
          <p className="text-slate-400 text-sm">Your QR code will be generated by the administrator after your account setup is complete.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* QR Preview */}
          <div className="glass-card p-6 rounded-2xl text-center space-y-4" style={{ border: "1px solid rgba(255,255,255,0.06)" }}>
            <h2 className="text-lg font-bold text-white">QR Code</h2>
            {qrDataUrl ? (
              <div className="bg-white p-4 rounded-2xl mx-auto w-fit shadow-xl shadow-indigo-500/10">
                <img src={qrDataUrl} alt="QR Code" className="w-48 h-48" />
              </div>
            ) : (
              <div className="w-48 h-48 mx-auto bg-slate-800 rounded-2xl animate-pulse" />
            )}

            <div className="flex gap-3">
              <button onClick={handleDownload} disabled={!qrDataUrl} className="btn-primary flex-1 py-2.5 rounded-xl text-sm flex items-center justify-center gap-2 disabled:opacity-50">
                <Download size={15} /> Download PNG
              </button>
              <button onClick={handlePrintCard} disabled={!qrDataUrl} className="flex-1 py-2.5 rounded-xl text-sm flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-700 text-white transition-colors disabled:opacity-50">
                <Printer size={15} /> Print Card
              </button>
            </div>
          </div>

          {/* Print Card Preview */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white">Printable Menu Card</h2>
            <p className="text-slate-400 text-sm">Download a print-ready card to place on your tables.</p>
            <div className="bg-slate-900/30 rounded-2xl p-4 border border-white/5">
              {/* The actual printable card */}
              <div
                ref={printCardRef}
                className="overflow-hidden mx-auto relative"
                style={{
                  width: 340,
                  height: 520,
                  fontFamily: "'Inter', sans-serif",
                  background: "linear-gradient(180deg, #0f172a 0%, #1e1b4b 100%)",
                  color: "white",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "space-between",
                  padding: "32px 20px 20px",
                  boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.5)",
                  borderRadius: "16px"
                }}
              >
                {/* Header: Logo and Name */}
                <div style={{ display: "flex", alignItems: "center", gap: "12px", width: "100%", justifyContent: "center" }}>
                  {restaurant.logo && (
                    <img crossOrigin="anonymous" src={restaurant.logo} alt="logo left" style={{ width: 44, height: 44, borderRadius: "50%", objectFit: "cover", border: "2px solid #fbbf24" }} />
                  )}
                  <h2 style={{ fontSize: "22px", fontWeight: 900, textTransform: "uppercase", letterSpacing: "1px", margin: 0, color: "#f8fafc", textAlign: "center" }}>
                    {restaurant.restaurantName}
                  </h2>
                  {restaurant.logo && (
                    <img crossOrigin="anonymous" src={restaurant.logo} alt="logo right" style={{ width: 44, height: 44, borderRadius: "50%", objectFit: "cover", border: "2px solid #fbbf24" }} />
                  )}
                </div>

                {/* Main Titles */}
                <div style={{ textAlign: "center", marginTop: "20px" }}>
                  <h1 style={{ fontSize: "42px", fontWeight: 900, color: "#fbbf24", margin: "0 0 8px 0", letterSpacing: "2px" }}>MENU</h1>
                  <p style={{ fontSize: "16px", color: "#cbd5e1", margin: 0, fontWeight: 500 }}>Scan to view our menu</p>
                </div>

                {/* QR Code */}
                <div style={{ background: "white", padding: "16px", borderRadius: "16px", marginTop: "16px", zIndex: 10, boxShadow: "0 10px 25px -5px rgba(0,0,0,0.5)" }}>
                  {qrDataUrl && <img src={qrDataUrl} alt="QR" style={{ width: 170, height: 170, display: "block" }} />}
                </div>

                {/* Footer Row (Images + Text) */}
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", width: "100%", marginTop: "auto", paddingTop: "16px" }}>
                  {/* Left Image */}
                  <div style={{ width: "70px", height: "70px", display: "flex", alignItems: "flex-end", justifyContent: "flex-start" }}>
                    {restaurant.qrLeftImage && (
                      <img crossOrigin="anonymous" src={restaurant.qrLeftImage} alt="Left decor" style={{ width: "100%", height: "100%", objectFit: "contain", filter: "drop-shadow(0 4px 6px rgba(0,0,0,0.3))" }} />
                    )}
                  </div>

                  {/* Center Text */}
                  <div style={{ paddingBottom: "10px", textAlign: "center", flex: 1 }}>
                    <p style={{ fontSize: "8px", color: "#94a3b8", margin: 0, textTransform: "uppercase", letterSpacing: "1px", fontWeight: 700 }}>
                      Developed by SHIKUR EBRAHIM
                    </p>
                  </div>

                  {/* Right Image */}
                  <div style={{ width: "70px", height: "70px", display: "flex", alignItems: "flex-end", justifyContent: "flex-end" }}>
                    {restaurant.qrRightImage && (
                      <img crossOrigin="anonymous" src={restaurant.qrRightImage} alt="Right decor" style={{ width: "100%", height: "100%", objectFit: "contain", filter: "drop-shadow(0 4px 6px rgba(0,0,0,0.3))" }} />
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
