"use client";

import { useAuth } from "@/hooks/useAuth";
import { useRestaurant } from "@/hooks/useRestaurant";
import { PageLoader, CardSkeleton } from "@/components/ui/Spinner";
import { StatusBadge } from "@/components/ui/Badge";
import { QrCode, List, UtensilsCrossed, CheckCircle } from "lucide-react";
import Link from "next/link";
import { getMenuUrl } from "@/lib/qrcode";

export default function DashboardPage() {
  const { user, loading: authLoading } = useAuth();
  const { restaurant, categories, menuItems, loading } = useRestaurant(
    user?.uid ?? null
  );

  if (authLoading || loading) return <PageLoader />;

  const menuUrl = restaurant?.slug ? getMenuUrl(restaurant.slug) : "";

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-black text-white font-display">Dashboard</h1>
        <p className="text-slate-400 mt-1">Welcome back, {user?.restaurantName}</p>
      </div>

      {/* Status banner */}
      <div className="glass-card p-5 rounded-2xl flex items-center gap-4" style={{ border: "1px solid rgba(255,255,255,0.08)" }}>
        <div className="w-12 h-12 rounded-xl bg-emerald-500/15 border border-emerald-500/20 flex items-center justify-center flex-shrink-0">
          <CheckCircle size={22} className="text-emerald-400" />
        </div>
        <div className="flex-1">
          <p className="text-white font-semibold">{user?.restaurantName}</p>
          <p className="text-slate-400 text-sm">Your restaurant is live and accepting customers</p>
        </div>
        <StatusBadge status={user?.status ?? "pending"} />
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {[
          { label: "Categories", value: categories.length, icon: List, color: "indigo", href: "/dashboard/categories" },
          { label: "Menu Items", value: menuItems.length, icon: UtensilsCrossed, color: "purple", href: "/dashboard/menu" },
          { label: "Available Items", value: menuItems.filter((m) => m.availability === "available").length, icon: CheckCircle, color: "emerald", href: "/dashboard/menu" },
        ].map(({ label, value, icon: Icon, color, href }) => (
          <Link
            key={label}
            href={href}
            className="glass-card p-5 rounded-2xl hover:border-white/20 transition-all group"
            style={{ border: "1px solid rgba(255,255,255,0.06)" }}
          >
            <div className={`w-10 h-10 rounded-xl bg-${color}-500/15 border border-${color}-500/20 flex items-center justify-center mb-3 group-hover:scale-110 transition-transform`}>
              <Icon size={18} className={`text-${color}-400`} />
            </div>
            <p className="text-3xl font-black text-white font-display">{value}</p>
            <p className="text-slate-400 text-sm mt-0.5">{label}</p>
          </Link>
        ))}
      </div>

      {/* QR preview */}
      {restaurant?.qrCodeUrl && (
        <div className="glass-card p-6 rounded-2xl" style={{ border: "1px solid rgba(255,255,255,0.08)" }}>
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6">
            <div className="w-32 h-32 rounded-2xl overflow-hidden bg-white p-2 flex-shrink-0">
              <img src={restaurant.qrCodeUrl} alt="QR Code" className="w-full h-full object-contain" />
            </div>
            <div className="flex-1">
              <h2 className="text-xl font-bold text-white mb-1">Your QR Code</h2>
              <p className="text-slate-400 text-sm mb-1">Share this code with your customers</p>
              <a
                href={menuUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-indigo-400 hover:text-indigo-300 text-sm font-mono transition-colors"
              >
                {menuUrl}
              </a>
              <div className="mt-4">
                <Link href="/dashboard/qr" className="btn-primary text-sm px-4 py-2 rounded-xl inline-flex items-center gap-2">
                  <QrCode size={14} /> Manage QR Code
                </Link>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Quick links */}
      {!restaurant?.qrCodeUrl && (
        <div className="glass-card p-6 rounded-2xl border border-amber-500/20" style={{ background: "rgba(245,158,11,0.05)" }}>
          <h3 className="text-white font-semibold mb-2">Getting Started</h3>
          <p className="text-slate-400 text-sm mb-4">
            Your QR code will be generated by the admin once your account is fully set up. In the meantime, start building your menu!
          </p>
          <div className="flex gap-3">
            <Link href="/dashboard/categories" className="btn-primary text-sm px-4 py-2 rounded-xl">
              Add Categories
            </Link>
            <Link href="/dashboard/menu" className="btn-primary text-sm px-4 py-2 rounded-xl" style={{ background: "#1e293b" }}>
              Add Menu Items
            </Link>
          </div>
        </div>
      )}
    </div>
  );
}
